---
title: "Assignment 2"
author: "Merle Nye"
date: "1/29/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries}
library(forecast)
library(dplyr)
library(tseries)
```

```{r}
ts
```

```{r load_data}
data <- read.csv("RenewableEnergy.csv")
```

```{r select_frame}
data <- data%>%
  select(Total.Biomass.Energy.Production, Total.Renewable.Energy.Production, Hydroelectric.Power.Consumption)
head(data)
tsdata<-ts(data[1:ncol(data)], frequency = 12)
head(tsdata)
```

```{r convert_object}
bio_ts<- ts(data$Total.Biomass.Energy.Production[1:ncol(data)], frequency = 12)

renew_ts <- ts(data$Total.Renewable.Energy.Production[1:ncol(data)], frequency = 12)

hydro_ts <- ts(data$Hydroelectric.Power.Consumption[1:ncol(data)], frequency = 12)

bio_ts
```

Make loop to get sd and mean then column bind em all

```{r find_sds}
ncol <- ncol(data)
mean_array=array(0,ncol) 
sd_array=array(0,ncol)
for(bio in 1:ncol){
  mean_array[bio]=mean(tsdata[ ,bio])  
  sd_array[bio]=sd(tsdata[ ,bio])   
}

results=cbind(mean_array,sd_array)
results
```

```{r plot_series}
plot.ts(tsdata[,1], col="blue", xlab = "Years", ylab = "Trillion BTU", main = "Total Biomass Energy Production")+
  abline(h=results[1,1], col = "red")+
  legend("topright",legend=c("Series Mean", "Monthly Total"), lty=c("solid","solid"),col=c("red", "blue"))
plot.ts(tsdata[,3], col="blue", , xlab = "Years", ylab = "Trillion BTU", main = "Total Renewable Energy Production")+
  abline(h=results[3,1], col="red") +
  legend("topright",legend=c("Series Mean", "Monthly Total"), lty=c("solid","solid"),col=c("red", "blue"))
plot.ts(tsdata[,2], col="blue", , xlab = "Years", ylab = "Trillion BTU", main = "Hydroelectric Power Consumption")+
  abline(h=results[2,1], col="red")+legend("topright",legend=c("Series Mean", "Monthly Total"), lty=c("solid","solid"),col=c("red", "blue"))

```

```{r cor_calc}
cor.test(ts[,1], ts[,2])
cor.test(ts[,1], ts[,3])
cor.test(ts[,2], ts[,3])

```

```{r ACF}

BP1_acf=Acf(tsdata[,1], lag.max=40, type="correlation", plot = TRUE)
RP_acf=Acf(tsdata[,2], lag.max=40, type="correlation", plot = TRUE)
HP_acf=Acf(tsdata[,3], lag.max=40, type="correlation", plot = TRUE)

plot(BP1_acf, main = "Autocorrelation of Total Biomass Energy Production")
plot(RP_acf, main = "Autocorrelation of Total Renewable Energy Production" )
plot(HP_acf, main = "Autocorrelation of Hydroelectric Power Consumption")

BP1_pacf=Pacf(tsdata[,1], lag.max=40, plot = TRUE)
RP_pacf=Pacf(tsdata[,2], lag.max=40,  plot = TRUE)
HP_pacf=Pacf(tsdata[,3], lag.max=40,  plot = TRUE)

plot(BP1_pacf, main = "Partial Autocorrelation of Total Biomass Energy Production")
plot(RP_pacf, main = "Partial Autocorrelation of Total Renewable Energy Production" )
plot(HP_pacf, main = "Partial Autocorrelation of Hydroelectric Power Consumption")

```
